"""
Run authentic Ollama extraction on Thai financial document OCR text
and record the exact response format for fixture and realistic offline mocking.
"""

import json
from pathlib import Path
import sys

ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR))

from src.llm_extractor import LLMExtractor

def main():
    print("=" * 70)
    print("🚀 Running Authentic Extraction via Ollama (qwen2.5:3b)...")
    print("=" * 70)

    extractor = LLMExtractor(default_model="qwen2.5:3b")

    is_online = extractor.is_ollama_running()
    print(f"Ollama Online Status: {is_online}")
    assert is_online, "Ollama must be running on localhost:11434"

    models = extractor.list_available_models()
    print(f"Available Models: {models}")

    sample_ocr = """--- Page 1 ---
### Extracted Text Content:
ใบเสร็จรับเงิน / ใบกำกับภาษี
บริษัท สมใจนึก สเตชั่นเนอรี่ จำกัด (สำนักงานใหญ่)
เลขประจำตัวผู้เสียภาษี: 0105558012345
วันที่: 18 กันยายน 2567
1. กระดาษถ่ายเอกสาร A4 70 แกรม จำนวน 5 รีม  550.00
2. ปากกาหมึกเจล 0.5 มม. จำนวน 2 กล่อง         120.00
3. แฟ้มเอกสารตราช้าง จำนวน 4 เล่ม              200.00
รวมเป็นเงิน (Subtotal):                       870.00
ภาษีมูลค่าเพิ่ม 7% (VAT):                      60.90
จำนวนเงินรวมทั้งสิ้น (Total):                  930.90
ขอขอบคุณที่ใช้บริการ
"""

    print("\nSending request to Ollama...")
    result = extractor.extract(ocr_markdown=sample_ocr, model_name="qwen2.5:3b", use_mock_if_offline=False)

    print("\n--- EXTRACTION RESULT METRICS ---")
    print(f"Is Mock: {result.is_mock}")
    print(f"Model Used: {result.model_used}")
    print(f"Latency: {result.latency_ms} ms")
    
    print("\n--- CHAIN OF THOUGHT (<think>) ---")
    print(result.thinking_process or "(No <think> tag generated by this model)")

    print("\n--- EXTRACTED STRUCTURED FIELDS ---")
    print(f"Vendor: {result.vendor_name}")
    print(f"Tax ID: {result.vendor_tax_id}")
    print(f"Date: {result.document_date}")
    print(f"Items: {len(result.line_items)}")
    for item in result.line_items:
        print(f"  - {item.description} x{item.quantity} {item.unit} @ {item.unit_price} = {item.total_price}")
    print(f"Subtotal: {result.subtotal}")
    print(f"VAT: {result.vat}")
    print(f"Total: {result.total_amount}")

    print("\n--- RAW LLM RESPONSE TEXT ---")
    print(result.raw_llm_response)

    extractor._save_real_fixture(result, "qwen2.5:3b")
    print("✅ Fixture saved successfully!")

if __name__ == "__main__":
    main()
